<a href="https://colab.research.google.com/github/Malaya47/Python_learnings/blob/main/Numpy_learnings.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Welcome to Colab!

In [ ]:
import numpy as np

In [ ]:
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [ ]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [ ]:
# creating a 1 dim array
a = np.array([1,2,3,4])
print(a)


[1 2 3 4]


(4,)

In [ ]:
a.shape

(4,)

In [ ]:
b = np.array([(1,2,3,4), (5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
b.shape

(2, 4)

In [ ]:
c = np.array([(1,2,3,4), (5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial Placeholders in numpy arrays

In [ ]:
# create a numpy array of zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
# create a numpy array of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# array of a particular value
z = np.full((5,4), 5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [ ]:
# create an identity matrix
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# create a numpy array with random values
b = np.random.random((3,4))
print(b)

[[0.1778339  0.93579634 0.9072368  0.57568949]
 [0.52915279 0.6239486  0.53980132 0.94764246]
 [0.6413826  0.60625231 0.86133596 0.28642602]]


In [ ]:
# random integer values array within a specific range
c = np.random.randint(10,100, (3,5))
print(c)

[[52 24 13 81 32]
 [47 22 58 89 60]
 [46 81 46 69 22]]


In [ ]:
# array of evenly spaced values --> specifying the number of values required
d = np.linspace(10,30,6)
print(d)

[10. 14. 18. 22. 26. 30.]


In [ ]:
# array of evenly spaced values --> specifying the step
e = np.arange(10,30,5)
print(e)


[10 15 20 25]


In [ ]:
# convert a list to a numpy array
list2 = [10,20,30,40,50]

np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 30 40 50]


numpy.ndarray

In [ ]:
# convert a tuple to numpy array
tuple2 = (10,20,30,40)

np_array = np.asarray(tuple2)
print(np_array)
type(np_array)

[10 20 30 40]


numpy.ndarray

Analysing a numpy array

In [ ]:
c = np.random.randint(10,90,(5,5))
print(c)

[[22 54 63 61 87]
 [69 33 72 20 48]
 [85 53 61 15 48]
 [35 11 86 38 85]
 [60 68 75 16 25]]


In [ ]:
# array dimension
# shape is nothing but the rows and colums
print(c.shape)

(5, 5)


In [ ]:
# number of dimensions
print(c.ndim)

2


In [ ]:
# number of elements in an array
print(c.size)

25


In [ ]:
# checking the data type of values in the array
print(c.dtype)

int64


Mathematical operations on a numpy array

In [ ]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2) # concatenate or joins two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [ ]:
# print(a)
# print(b)

[[3 5 4]
 [5 5 9]
 [1 5 7]]
[[19 19 14]
 [13 19 12]
 [16 15 12]]


In [ ]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[22 24 18]
 [18 24 21]
 [17 20 19]]
[[-16 -14 -10]
 [ -8 -14  -3]
 [-15 -10  -5]]
[[ 57  95  56]
 [ 65  95 108]
 [ 16  75  84]]
[[0.15789474 0.26315789 0.28571429]
 [0.38461538 0.26315789 0.75      ]
 [0.0625     0.33333333 0.58333333]]


In [ ]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [ ]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[16 21 17]
 [15 22 21]
 [21 24 25]]
[[-10  -5 -13]
 [-11 -12 -17]
 [ -3 -10  -7]]
[[ 39 104  30]
 [ 26  85  38]
 [108 119 144]]
[[0.23076923 0.61538462 0.13333333]
 [0.15384615 0.29411765 0.10526316]
 [0.75       0.41176471 0.5625    ]]


Array Manipulation

In [ ]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[4 9 4]
 [3 6 9]]
(2, 3)


In [ ]:
# transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[4 3]
 [9 6]
 [4 9]]
(3, 2)


In [ ]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[4 3]
 [9 6]
 [4 9]]
(3, 2)


In [ ]:
# reshaping a array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[1 2 1]
 [1 5 4]]
(2, 3)


In [ ]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[1 2]
 [1 1]
 [5 4]]
(3, 2)
